name: Preparing
description: preparing to run the checks

inputs:
  cache-key:
    required: true
    description: build cache key

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install packages
      shell: bash
      run: yarn install
