name: Check comment
description: show comment with results

inputs:
  token:
    required: true
    description: GITHUB_TOKEN
  title:
    required: true
    description: title
  eslint:
    required: true
    description: ESLint
  prettier:
    required: true
    description: Prettier
  unit:
    required: true
    description: Unit

runs:
  using: composite
  steps:
      - name: Comment
        uses: sendsay-ru/rewritable-pr-comment@v1.0.1
        with:
          message: "${{ inputs.title }} \n\n
                  | ESLint | Prettier | Unit |\n
                  | --- | --- | --- |\n
                  |  ${{ inputs.eslint }}  |  ${{ inputs.prettier }}  |  ${{ inputs.unit }}  |\n\n
                  [🔗 See details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          GITHUB_TOKEN: ${{ inputs.token }}
          COMMENT_IDENTIFIER: "comment-check-result"
