# rendered by https://www.npmjs.com/package/github-actions-checks
name: Checks
on:
  pull_request:
  push:
    branches:
      - stable
      - master
      - main
    tags:
      - v**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    outputs:
      eslint: ${{ steps.eslint.outputs.result }}
      prettier: ${{ steps.prettier.outputs.result }}
      playwright: ${{ steps.playwright.outputs.result }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Preparing
        uses: ./.github/actions/check-install

      - name: Pre command
        if: always()
        shell: bash
        run: npx playwright install --with-deps

      - name: ESLint
        id: eslint
        if: always()
        uses: ./.github/actions/check-run
        with:
          script: yarn eslint

      - name: Prettier
        id: prettier
        if: always()
        uses: ./.github/actions/check-run
        with:
          script: yarn prettify

      - name: Playwright
        id: playwright
        if: always()
        uses: ./.github/actions/check-run
        with:
          script: yarn e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifacts
          retention-days: 30
          path: |
            playwright-report
            playwright-artifacts

  tests:
    runs-on: ubuntu-latest

    outputs:
      unit: ${{ steps.unit.outputs.result }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Preparing
        uses: ./.github/actions/check-install

      - name: Unit
        id: unit
        if: always()
        uses: ./.github/actions/check-run
        with:
          script: yarn unit
