name: Check PR
on: [pull_request]

env:
  NODE_ENV: CI
  FORCE_COLOR: 1
  PROGRESS_TITLE: "### 👷 Checks in progress..."
  SUCCESS_TITLE: "### ✅ Checks completed successfully!"
  FAILURE_TITLE:  "### 🚫 Checks were executed with errors!"
  PROGRESS_ICON: "🏄🏻‍♂️"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  checks: write
  pull-requests: write

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Starting comment
        uses: ./.github/actions/check-comment
        with:
          title: ${{ env.PROGRESS_TITLE }}
          eslint: ${{ env.PROGRESS_ICON }}
          prettier: ${{ env.PROGRESS_ICON }}
          unit: ${{ env.PROGRESS_ICON }}
          token: ${{ secrets.GITHUB_TOKEN }}

  checks:
    needs: start
    runs-on: ubuntu-latest

    outputs:
      eslint: ${{ steps.eslint.outputs.result }}
      prettier: ${{ steps.prettier.outputs.result }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Preparing
        uses: ./.github/actions/check-install
        with:
          cache-key: cache-turbo-checks-${{ github.event.pull_request.number }}

      - name: Eslint
        id: eslint
        if: always()
        uses: ./.github/actions/check-run
        with:
          script: npm eslint

      - name: Prettier
        id: prettier
        if: always()
        uses: ./.github/actions/check-run
        with:
          script: yarn pretify

  tests:
    needs: start
    runs-on: ubuntu-latest

    outputs:
      unit: ${{ steps.unit.outputs.result }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Preparing
        uses: ./.github/actions/check-install
        with:
          cache-key: cache-turbo-checks-${{ github.event.pull_request.number }}

      - name: Unit
        id: unit
        if: always()
        uses: ./.github/actions/check-run
        with:
          script: yarn test

  report:
    needs: [checks,tests]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Title
        id: title
        run: |
          if [[ ${{ needs.checks.result }} == 'success' ]] && [[ ${{ needs.tests.result }} == 'success' ]]; then echo "str=${{ env.SUCCESS_TITLE }}" >> $GITHUB_OUTPUT; else echo "str=${{ env.FAILURE_TITLE }}" >> $GITHUB_OUTPUT; fi

      - name: Final comment
        uses: ./.github/actions/check-comment
        with:
          title: ${{ steps.title.outputs.str }}
          eslint: ${{ needs.checks.outputs.eslint }}
          prettier: ${{ needs.checks.outputs.prettier }}
          unit: ${{ needs.tests.outputs.unit }}
          token: ${{ secrets.GITHUB_TOKEN }}
